name: task_pomodoro
description: "A task-based Pomodoro timer app."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  flutter_launcher_icons: ^0.9.2
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  linux: true
  macos: true
  windows: true
  minSdkVersion: 21
  image_path: "assets/icon/app_icon.png"  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.png
